[pytest]
markers =
    model: Макер для модели
    view: Маркер для предсталвения
    controller: Маркер для контроллера
    debug: Маркер для отладки

log_cli = false
log_cli_level = INFO

; Отключение маскирования кириллицы
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True